### ISSUE TITLE
Adjust tailwind in the project

### ISSUE THREAD

**Issue by jv-farias** [dcTeam23/cat-list#17]
### Atualmente, o Tailwind em nosso projeto está precisando de alguns ajustes, pois não está funcionando de maneira correta, ocasionando atraso no fluxo de desenvolvimento.
---

#### Exemplo: 
https://github.com/dcTeam23/cat-list/assets/84153149/3a3359d5-fb4c-4f4c-b40e-7c3b09f146c7

**Comment by AbraaoAlves** [comment]
Você pode anexar um vídeo mpa aqui na issue TB, não precisa pedirem p os devs se ligarem em outra plataforma p ver o bug
